//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reklama.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReklamaCustomEntities : DbContext
    {
        public ReklamaCustomEntities()
            : base("name=ReklamaCustomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banners> Banners { get; set; }
        public virtual DbSet<BannerTypes> BannerTypes { get; set; }
        public virtual DbSet<Images> Images { get; set; }
    }
}
